### ISSUE TITLE
Send spring programme to FooCafe

### ISSUE THREAD

**Issue by olleolleolle** [malmorb/malmorb.github.com#30]
# TODO

- [ ]  themes for each event
- [ ]  enough information on each event to publish it when the time comes
- [x]  dates
- [x]  make a spreadsheet (ask @olleolleolle for the link)
